# Generated by Django 2.0 on 2018-05-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='followers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='retweets',
            field=models.IntegerField(),
        ),
    ]
